export const predefinedEdgeStyles = {
    single: {
        topLeftCorner: "┌",
        topRightCorner: "┐",
        bottomLeftCorner: "└",
        bottomRightCorner: "┘",
        horizontalSeparator: "─",
        verticalSeparator: "┼",
        vertical: "│",
        topCenter: "┬",
        bottomCenter: "┴",
        verticalRowLeft: "├",
        verticalRowRight: "┤",
    },

    bold: {
        topLeftCorner: "╓",
        topRightCorner: "╖",
        bottomLeftCorner: "╙",
        bottomRightCorner: "╜",
        horizontalSeparator: "─",
        verticalSeparator: "┼",
        vertical: "║",
        topCenter: "╥",
        bottomCenter: "╨",
        verticalRowLeft: "╟",
        verticalRowRight: "╢",
    },

    rounded: {
        topLeftCorner: "╭",
        topRightCorner: "╮",
        bottomLeftCorner: "╰",
        bottomRightCorner: "╯",
        horizontalSeparator: "─",
        verticalSeparator: "┼",
        vertical: "│",
        topCenter: "┬",
        bottomCenter: "┴",
        verticalRowLeft: "├",
        verticalRowRight: "┤",
    },

    dotted: {
        topLeftCorner: "+",
        topRightCorner: "+",
        bottomLeftCorner: "+",
        bottomRightCorner: "+",
        horizontalSeparator: ".",
        verticalSeparator: "+",
        vertical: "|",
        topCenter: "+",
        bottomCenter: "+",
        verticalRowLeft: "+",
        verticalRowRight: "+",
    },

    thick: {
        topLeftCorner: "╔",
        topRightCorner: "╗",
        bottomLeftCorner: "╚",
        bottomRightCorner: "╝",
        horizontalSeparator: "═",
        verticalSeparator: "╬",
        vertical: "║",
        topCenter: "╦",
        bottomCenter: "╩",
        verticalRowLeft: "╠",
        verticalRowRight: "╣",
    },

    minimal: {
        topLeftCorner: " ",
        topRightCorner: " ",
        bottomLeftCorner: " ",
        bottomRightCorner: " ",
        horizontalSeparator: "-",
        verticalSeparator: "+",
        vertical: "|",
        topCenter: "+",
        bottomCenter: "+",
        verticalRowLeft: "+",
        verticalRowRight: "+",
    },

    heavyDashed: {
        topLeftCorner: "╒",
        topRightCorner: "╕",
        bottomLeftCorner: "╘",
        bottomRightCorner: "╛",
        horizontalSeparator: "═",
        verticalSeparator: "╪",
        vertical: "│",
        topCenter: "╤",
        bottomCenter: "╧",
        verticalRowLeft: "╞",
        verticalRowRight: "╡",
    },

    double: {
        topLeftCorner: "╔",
        topRightCorner: "╗",
        bottomLeftCorner: "╚",
        bottomRightCorner: "╝",
        horizontalSeparator: "═",
        verticalSeparator: "╬",
        vertical: "║",
        topCenter: "╦",
        bottomCenter: "╩",
        verticalRowLeft: "╠",
        verticalRowRight: "╣",
    },
};
